

const characters = [
  {id: 1, name: "Thor"},
  {id: 2, name: "Iron Man"},
  {id: 3, name: "Ant Man"},
  {id: 4, name: "The Wasp"},
  {id: 5, name: "Hulk"},
  {id: 6, name: "Captain America"},
  {id: 7, name: "Hawkeye"},
  {id: 8, name: "Quicksilver"},
  {id: 9, name: "Scralet Witch"},
  {id: 10, name: "Hercules"},
  {id: 11, name: "Black Panther"},
  {id: 12, name: "Black Knight"},
  {id: 13, name: "Black Widow"},
  {id: 14, name: "Swordsman"},
  {id: 15, name: "Mantis"},
  {id: 16, name: "Beast"},
  {id: 17, name: "Moondragon"},
  {id: 18, name: "Patsy Walker"},
  {id: 19, name: "Wonder Man"},
  {id: 20, name: "Two-Gun Kid"},
  {id: 21, name: "Ms. Marvel"},
  {id: 22, name: "Falcon"},
  {id: 23, name: "Tigra"},
  {id: 24, name: "She-Hulk"},
  {id: 25, name: "Captain Marvel"},
  {id: 26, name: "Starfox"},
  {id: 27, name: "Namor"},
  {id: 28, name: "Doctor Druid"},
  {id: 29, name: "Mockingbird"},
  {id: 30, name: "War Machine"},
  {id: 31, name: "Thing"},
  {id: 32, name: "Moon Knight"},
  {id: 33, name: "Firebird"},
  {id: 34, name: "U.S. Agent"},
  {id: 35, name: "Human Torch"},
  {id: 36, name: "Living Lightning"},
  {id: 37, name: "Spider-Woman"},
  {id: 38, name: "Machine Man"},
  {id: 39, name: "Darkhawk"},
  {id: 40, name: "Demolition Man"},
  {id: 41, name: "Forgotten One"},
  {id: 42, name: "Mister Fantastic"},
  {id: 43, name: "Invisible Woman"},
  {id: 44, name: "Quasar"},
  {id: 45, name: "Sersi"},
  {id: 46, name: "Stingray"},
  {id: 47, name: "Spider-Man"},
  {id: 48, name: "Sandman"},
  {id: 49, name: "Rage"},
  {id: 50, name: "Crystal"},
  {id: 51, name: "Thunderstrike"},
  {id: 52, name: "Justice"},
  {id: 53, name: "Firestar"},
  {id: 54, name: "Triathlon"},
  {id: 55, name: "Silverclaw"},
  {id: 56, name: "Jack of Hearts"},
  {id: 58, name: "Captain Britain"},
  {id: 59, name: "Luke Cage"},
  {id: 60, name: "Wolverine"},
  {id: 61, name: "Sentry"},
  {id: 62, name: "Echo"},
  {id: 63, name: "Ares"},
  {id: 64, name: "Amadeus Cho"},
  {id: 65, name: "Jocasta"},
  {id: 66, name: "Stature"},
  {id: 67, name: "Vision"},
  {id: 68, name: "Maria Hill"},
  {id: 69, name: "Valkyrie"},
  {id: 70, name: "Nova"},
  {id: 71, name: "Sharon Carter"},
  {id: 72, name: "Iron Fist"},
  {id: 73, name: "Xorr the God-Jewel"},
  {id: 74, name: "Victoria Hand"},
  {id: 75, name: "Rick Jones"}, 
  {id: 76, name: "Whizzer"},
  {id: 77, name: "Marrina"},
  {id: 78, name: "Yellowjacket"},
  {id: 79, name: "Magdalene"},
  {id: 80, name: "Deathcry"},
  {id: 81, name: "Moira Brandon"},
  {id: 82, name: "Masque"},
  {id: 83, name: "Doctor Strange"},
  {id: 84, name: "Yondu"},
  {id: 85, name: "Martinex"},
  {id: 86, name: "Charlie-27"},
  {id: 87, name: "Nikki"},
  {id: 88, name: "Starhawk"},
  {id: 89, name: "Aleta Ogord"},
  {id: 90, name: "Vance Astro"},
  {id: 91, name: "Ravonna"},


];

export default characters;